version: "3.9"
services:
  app:
    container_name: docker-share-app
    build: .
    depends_on:
      - redis
    ports:
      - 8080:3000
  redis:
    container_name: docker-share-redis
    image: redis:5.0.14-alpine